n = 5
t = 1
t_reconstruction = 3
start_time = "2025-09-09T14:10:00Z"

[[nodes]]
id = 1
multiaddr = "/dns/dkg-testnet1.dcipher.network/tcp/80"
adkg_pk = "3ywr0W6ZEscpJYJ4yznY+Ic1lCLJZJxOhK9iz/8r53M="
peer_id = "12D3KooWKBZgjNMhZhb7aKTTbSFM91QeGec6KQTNfJaKqqw6DzJ3"

[[nodes]]
id = 2
multiaddr = "/dns/dkg-testnet2.dcipher.network/tcp/80"
adkg_pk = "0Lz3gnmDryH21FT7V039AVnOuPIWxiaPE6XhV8bsICA="
peer_id = "12D3KooWPRv6Rizhyr94UaT5WXsrZydE8mFkjitR7bF95tCWV657"

[[nodes]]
id = 3
multiaddr = "/dns/dkg-testnet3.dcipher.network/tcp/80"
adkg_pk = "6YMJVN9nsNCht9eOJrmU0JlZhPAJM+dm7yvbnM6kF+A="
peer_id = "12D3KooWDAwFMox7uzJ9yRzSdNesgbUhNhXoWXFGUuYSFA24jk9t"

[[nodes]]
id = 4
multiaddr = "/dns/dciphertest.ata.network/tcp/7777"
adkg_pk = "kgIm7IgwJYktWZ24ym1x/nL9KLaGWw1cT5QuYOZLlyQ="
peer_id = "12D3KooWP5191tQRaMGbKXVC5Aja1wPNdiZfRbAv5FKi5ZfszDfF"

# storswift
[[nodes]]
id = 5
multiaddr = "/ip4/47.104.170.105/tcp/7890"
adkg_pk = "ySf1t0UZx6ol5L9iLy7icddHtiKBb8kFuKWpNWa1w6g="
peer_id = "12D3KooWDLZZZrLeQ5AgY9x3mmkpbThB8XVyyrhTXyJUDPeD9pUQ"
