app_name = "dcipher-testnet"
curve_id = "Bn254G1"
hash_id = "Keccak256"
adkg_version = "v0.1"
generator_g = "7YJERmicw+ViR4UEOBNRsutI+TAFzkJvUTw+HcON7zU="
generator_h = "pkFRH8H+G1oQ8QwBySV9EXRStnDxC5BpzpQudrXcLLw="
adkg_scheme_name = "DXKR23-Bn254G1-Keccak256"
output_generator = "mY6Tk5INSDpyYL+3MftdJfGqSTM1qecSl+SFt67zEsIYAN7vEh8edkJqAGZeXER5Z0Mi1Pde2t1G3r1c2ZL27Q=="
