adkg_scheme_name = "DYX20-Bn254G1-Keccak256"
genesis_timestamp = 1754299900
group_pk = "x0S2fTdbOYvPRn9bxG/08bS0CndoLLo7dfDsKvX6thw="

[[node_pks]]
id = 1
pk = "nqOHbB8vkV6DT42B7FE6fTD74HIbd1c/cSZAyEejB6w="
peer_id = "12D3KooWNynkcrc6tS9EBQMe2J2BsebZq7bU4mgXMatDRer8eDbb"
multiaddr = "/dns/drand.diadata.org/tcp/4242"

[[node_pks]]
id = 2
pk = "nVE9g/pdzUlrR1yQ31ZIFTI5cuJR/VxjleZTBI5UUUo="
peer_id = "12D3KooWMTwoV3DPt1GUJfZdyDvmX4ankVswnPDK92sB9kePXukr"
multiaddr = "/dns/pl1-rpc.testnet.drand.sh/tcp/8080"

[[node_pks]]
id = 3
pk = "zUC725BhvmwtYPkbzdzeO+usydjv6MG0oA14lH+bQhw="
peer_id = "12D3KooWHZveoayqsNdUymq2ZGg4T3cqRvweEQgHBjHkNB1Mb5DH"
multiaddr = "/dns/testnet-1.drand.theqrl.org/tcp/4421"

[[node_pks]]
id = 4
pk = "2xQBKgJHL0PAeqV6eFV7dMYJJn8LNtMufbY+5dPtuM0="
peer_id = "12D3KooWDGEa22QJC5uoDuKiBDWrXht9PH5fmqbjse15uWywB5Dj"
multiaddr = "/ip4/193.5.234.66/tcp/7777"

[[node_pks]]
id = 5
pk = "jYgBqOXhEZ7TpPcUOnPO6vzHEdwqijdzplbfN02JcDw="
peer_id = "12D3KooWT3SmyBzmT2RY5pZhr5wHSZ5WkA8EwN8UvgUKZxhivcvw"
multiaddr = "/ip4/47.104.170.105/tcp/7890"

[[node_pks]]
id = 6
pk = "3x/9n9NfqwCXom3KgVuopJGJ5+gJdrLlMo1lRjtkUuI="
peer_id = "12D3KooWBvRVuRLWRhyka1APsNg74gry6K9MSYPg4HmNPAjGcSte"
multiaddr = "/dns/dciphertest.ata.network/tcp/7777"
