n = 7
t = 2
t_reconstruction = 3
start_time = "2025-09-30T14:00:00Z"

# Randamu
[[nodes]]
id = 1
multiaddr = "/dns/mainnet1.dkg.dcipher.network/tcp/8080"
adkg_pk = "hw5NTuNWxYL/JBKLz55pjjnhThCpcu1CtX9JxjVcoG0="
peer_id = "12D3KooWJvYaMqERGdUagqka5YwCpN7FA9enHbonXNhdnifCLRXm"

# Randamu
[[nodes]]
id = 2
multiaddr = "/dns/mainnet2.dkg.dcipher.network/tcp/8080"
adkg_pk = "15QtyW0mCFRzZNw5y/M19JAxhh/V20a1mHjaDp7OCh4="
peer_id = "12D3KooWBzwNW9WKAGyn1nBkEoMQA86go3xCYVf9Sn8rxfQTC7HD"

# ATA
[[nodes]]
id = 3
multiaddr = "/dns/dcipher.ata.network/tcp/7778"
adkg_pk = "k++eRlBlg6L2lcGcQp/sWcF6ejgOJ82rwtFJu+o+ubc="
peer_id = "12D3KooWFjbRVYTGRDLMFCXJukiTjGY2h8yA53SNg7EoPDdXzg9r"

# IPFSForce
[[nodes]]
id = 4
multiaddr = "/dns/dci-mainnet.ipfsforce.com/tcp/7777"
adkg_pk = "i36ck1eJ8dzwMpnuq94oTd9qBenuTWlI0kgK1ILR7m4="
peer_id = "12D3KooWJX9TK3zWadqv2DeG1fsUbrmfxVLJqzGfPr23QGetvDrx"

# Storswift
[[nodes]]
id = 5
multiaddr = "/dns/labs.secureweb3.com/tcp/8890"
adkg_pk = "m6GO4Sq+CMRB2D/IpibC59E+fiN+1Nnv+G8NhskQey8="
peer_id = "12D3KooWSBJZ3Z3Qr5GsdNTRC3ePbNdApURWK35N4iAXzjv6rKh9"

# Grüne Zwiebel
[[nodes]]
id = 6
multiaddr = "/dns/misc.quimian.com/tcp/5050"
adkg_pk = "iVtJMj47NRCvjdjlediL8u3IX7Flh2sSjP7DSBs8AAs="
peer_id = "12D3KooWDkCVCePZYXrHYhjVM9d7CLKSMHvUgpon8EPZKp341nDU"

# DIA Data
[[nodes]]
id = 7
multiaddr = "/dns/drand.diadata.org/tcp/4243"
adkg_pk = "2Am7AFGsLths8uYtNFLI+iQ6Yz3K3Y9q1+LKdMcrSkA="
peer_id = "12D3KooWB8nSysj9DNLgeWdS3aTbb2htiPHn99LA5jUuDrreMadH"
