app_name = "dcipher-mainnet"
curve_id = "Bn254G1"
hash_id = "Keccak256"
adkg_version = "v0.1"
generator_g = "jQq6k7FT4wDe6xUhFDT/ugVNw6wZons33ljhfXMIxrg="
generator_h = "7G86aBjXNwcx16jxxbeyO1hNNPB4BqL6w9vLw35wk2U="
adkg_scheme_name = "DXKR23-Bn254G1-Keccak256"
output_generator = "mY6Tk5INSDpyYL+3MftdJfGqSTM1qecSl+SFt67zEsIYAN7vEh8edkJqAGZeXER5Z0Mi1Pde2t1G3r1c2ZL27Q=="
